server:
  port: 8081

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: health,env,info,prometheus

client-service:
  server-url: "http://localhost:8080"
  way-to-do: executor #manually or executor
  amount-of-requests-for-getting-process: 100 # amount of tasks for 'executor' case or amount of threads for 'manually' case
  amount-of-requests-for-putting-process: 100 # amount of tasks for 'executor' case or amount of threads for 'manually' case
  amount-of-threads: 100 #only for executor case
  list-of-ids:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
